stages:
  - terraform:lint

.base-terraform:
  image: 
    name: "hashicorp/terraform"
    entrypoint: [""]
  before_script:
    - terraform version

tf-fmt:
  stage: terraform:lint
  extends: .base-terraform
  script:
    - terraform fmt -check -recursive
  
tf-validate:
  stage: terraform:lint
  extends: .base-terraform
  script: |
      terraform init
      terraform validate

