on: push

jobs:
 terraform-lint:
  runs-on: ubuntu-latest
  container: "hashicorp/terraform"
  steps:
     - name: Check repository code
       uses: actions/checkout@v2
     - name: Check Terraform version 
       run: terraform version
     - name: Check Terraform code format
       run: terraform fmt -check -recursive
     - name: Validate Terraform code
       run: |
          terraform -chdir=examples/ init -backend-config="token=${{ secrets.TERRAFORM_LOGIN_TOKEN }}"
          terraform -chdir=examples/ validate